-- Baseline: captures schema as it existed prior to Flyway adoption
-- (previously managed by Hibernate ddl-auto: update).

CREATE TABLE man_accounts (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    man_id        VARCHAR(255),
    symbol        VARCHAR(255),
    bank_balance  NUMERIC(19,8),
    shares_owned  NUMERIC(19,8),
    cost_basis    NUMERIC(19,8),
    market_value  NUMERIC(19,8),
    updated_at    TIMESTAMP(6)
);

CREATE TABLE transactions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    man_id           VARCHAR(255),
    symbol           VARCHAR(255),
    amount           NUMERIC(19,8),
    shares           NUMERIC(19,8),
    price            NUMERIC(19,8),
    transaction_type VARCHAR(255),
    timestamp        TIMESTAMP(6)
);

CREATE TABLE quotes (
    id                                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol                              VARCHAR(255),
    name                                VARCHAR(255),
    exchange                            VARCHAR(255),
    currency                            VARCHAR(255),
    datetime                            DATE,
    timestamp                           BIGINT NOT NULL,
    open                                NUMERIC(19,8),
    high                                NUMERIC(19,8),
    low                                 NUMERIC(19,8),
    close                               NUMERIC(19,8),
    volume                              BIGINT NOT NULL,
    previous_close                      NUMERIC(19,8),
    change                              NUMERIC(19,8),
    percent_change                      NUMERIC(19,8),
    average_volume                      BIGINT NOT NULL,
    is_market_open                      BOOLEAN NOT NULL,
    fifty_two_week_low                  NUMERIC(19,8),
    fifty_two_week_high                 NUMERIC(19,8),
    fifty_two_week_low_change           NUMERIC(19,8),
    fifty_two_week_high_change          NUMERIC(19,8),
    fifty_two_week_low_change_percent   NUMERIC(19,8),
    fifty_two_week_high_change_percent  NUMERIC(19,8),
    fifty_two_week_range                VARCHAR(255),
    created_at                          TIMESTAMP(6)
);

CREATE TABLE price_history (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol     VARCHAR(255),
    date       DATE,
    open       NUMERIC(19,8),
    high       NUMERIC(19,8),
    low        NUMERIC(19,8),
    close      NUMERIC(19,8),
    volume     BIGINT NOT NULL,
    created_at TIMESTAMP(6),
    CONSTRAINT uk4nhsgcttyx8l3ij5s7mgsraj7 UNIQUE (symbol, date)
);
