CREATE TABLE account_snapshots (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    man_id           VARCHAR(255),
    symbol           VARCHAR(255),
    transaction_id   BIGINT,
    price            NUMERIC(19,8),
    bank_balance     NUMERIC(19,8),
    shares_owned     NUMERIC(19,8),
    cost_basis       NUMERIC(19,8),
    market_value     NUMERIC(19,8),
    gain             NUMERIC(19,8),
    gain_percent     NUMERIC(19,8),
    timestamp        TIMESTAMP(6)
);
