server:
  port: 8085

spring:
  datasource:
    url: "${DATASOURCE_URL}"
    username: "${DATASOURCE_USERNAME}"
    password: "${DATASOURCE_PASSWORD}"
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      max-lifetime: 180000
      idle-timeout: 120000
  jpa:
    hibernate:
      ddl-auto: update
