server:
  port: 8083

spring:
  datasource:
    url: "${DATASOURCE_URL}"
    username: "${DATASOURCE_USERNAME}"
    password: "${DATASOURCE_PASSWORD}"
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      max-lifetime: 180000
      idle-timeout: 120000
  jpa:
    hibernate:
      ddl-auto: update

twelvedata:
  apikey: "${TWELVEDATA_API_KEY}"
  baseurl: "https://api.twelvedata.com/"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

custom:
  price-refresh: 1d